### ISSUE TITLE
Sailor on paired-end data

### ISSUE THREAD

**Issue by CelineLabbeCurie** [YeoLab/FLARE#3]
Hello,

I've used Sailor to find edit sites (C-to-U) but as I have paired-end data (at least I supposed it's because of that), Sailor output contains only editing on the minus strand et none on the plus strand. 
Is there a way to use Sailor on paired-end data please ?

Best regards

**Comment by garifalloj** [comment]
Hello,

I would also like to understand the best way to run paired-end data using SAILOR. I have been able to run the single-end data with the appropriate outputs. I believe in the previous version of the program, there was a configuration field for selecting single or paired-end, but I was not able to find the same editable field in the snakefile.

Thanks for any advice!

**Comment by ekofman** [comment]
SAILOR does not handle paired end data well (coverage is double-counted) currently. We are working on ways to make this available. Sorry for the delay in responding.
